apiVersion: v2
name: minio-platform
description: Обёртка над внешним чартом MinIO.
type: application
version: 0.1.0
dependencies:
  - name: minio
    version: 17.0.21
    repository: oci://registry-1.docker.io/bitnamicharts
