apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-dashboard
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sales-dashboard
          image: sales-dashboard:dev
